name: Redirect checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npx vercel dev --listen 9000 --confirm --login ${{ secrets.VERCEL_TOKEN }} &
        npx wait-on http-get://127.0.0.1:9000/docs -v -c waitOnConfig.json
        npm run test:unit
